#!/bin/bash
DOMAIN=${1:-magento2.dev}
VERSION=${2:-2.3.3}

curl -s https://raw.githubusercontent.com/topvalue/m2_docker-test/master/lib/template | bash
bin/download $VERSION

echo "Your system password has been requested to add an entry to /etc/hosts..."
echo "127.0.0.1 ::1 $DOMAIN" | sudo tee -a /etc/hosts

bin/setup $DOMAIN
