# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 30.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-8
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    environment:
      - TZ=Asia/Bangkok

  phpfpm:
    image: markoshust/magento-php:7.3-fpm-5
    links:
      - db
    volumes: *appvolumes
    environment:
      - TZ=Asia/Bangkok

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - TZ=Asia/Bangkok

  redis:
    image: redis:5.0
    environment:
      - TZ=Asia/Bangkok

  elasticsearch:
    image: markoshust/magento-elasticsearch:6.5.4-0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - TZ=Asia/Bangkok

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    environment:
      - TZ=Asia/Bangkok

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.3-fpm-5
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
